### PR TITLE
Auto gen wrappers

### PR DESCRIPTION
**Pull request by abelnation**
This PR will track the TODO's necessary to convert the autogen branch to master.  [Previous PR with discussion](https://github.com/jovyan/pythreejs/pull/57)
@jasongrout @SylvainCorlay @martinal @vidartf 

- [x] Cleanup commented code
- [x] [Get repo updated with latest ipywidgets changes](https://github.com/jovyan/pythreejs/issues/87)
- [ ] [Audit for critical unimplemented features](https://github.com/jovyan/pythreejs/issues/89)
- [ ] (other todo's)

### CODE REVIEW

**Comment by vidartf** [comment]
I'm starting to play around with this again, and would love if someone more involved could merge master into the autogen branch (or rebase it). I did a quick and dirty attempt, but am getting some errors where I don't know where to start in order to fix.

**Comment by jasongrout** [comment]
I'm getting pythreejs to work on jupyterlab (which is cleaning up some of the circular dependencies in the lab files), and then can take a crack at this merge.

**Comment by honorabel** [comment]
Given that the autogen branch ignores most of the original pythreejs code, I might just cherrypick the jupyterlab specific setup files and any other non-core-wrapper code into the autogen branch.

**Comment by vidartf** [comment]
I got my quick and dirty attempt far enough along that I at least can play a little with it (but many things does not work). I found a few Python-side issues this way:
 - [ ] `Group` should inherit `Object3D`.
 - [ ] The old materials defined in `pythreejs.py` are not compatible with the new ones (e.g. `LambertMaterial` vs `MeshLambertMaterial`). The trait validation fails. Should the definitions in `pythreejs.py` be removed?

**Comment by vidartf** [comment]
Another issue:
 - [ ] `Union` traits need to have `.tag(sync=True, **widget_serialization)` on the Union as well. Example: the `Mesh` class does not sync the `geometry` attribute without it.

**Comment by vidartf** [comment]
- [ ] `MeshLambertMaterial` and `MeshPhongMaterial` does not render for me. No idea why yet. I can only get `MeshStandardMaterial` to show. Any other material type other than those three generate exceptions on the Javascript side.

**Comment by vidartf** [comment]
@abelnation / @honorabel : Did you have any thoughts on how to put together renderer/camera/scene/controllers in a configurable way? Now it seems to be hard-coded in the `ThreeWidget` javascript code (or?).

**Comment by honorabel** [comment]
@vidartf The goal was to provide a "default" viewer that was "good enough".  I started to add some special variables to ThreeObjects that allowed some level of configuration.  I prefixed all these variables with an underscore, e.g. for the shading type (to allow smooth vs. faceted shading).  I'm not sure if that's a good model, or if we should create just one `_renderOptions` dictionary that contains all pythreejs specific configurations for the default renderer.  

It is possible to use pythreejs to setup an entire scene with separate camera, scene, lights, etc.  It's a bit more involved, but one thought was that if you want something specially custom, that just putting all the elements together yourself is probably the best way, rather than making our "good enough" render setup fully customizable.

**Comment by vidartf** [comment]
> It is possible to use pythreejs to setup an entire scene with separate camera, scene, lights, etc.

Is this possible from the Python side, or would this need to be done on the JS side?

**Comment by honorabel** [comment]
@vidartf In theory ;) There may be a bug or two, but test.ipynb has an example of setting everything up manually.  Might have to dig into the custom wrapper code for the renderer to see what might be the problem.

**Comment by vidartf** [comment]
Thanks. As far as I can tell `WebGLRenderer.render()` does not have a way of adding controllers? I.e. it is only useful for rendering one frame at the time? If so, I will try to change it or add another class to better emulate the behavior of the current `Renderer` class.

**Comment by honorabel** [comment]
@vidartf Philosophically, (and @jasongrout @SylvainCorlay, feel free to weigh in here), We should try to keep the api/functionality of the three.js wrappers to mirror the three.js api as much as possible.  Any custom functionality should be provided by a new custom wrapper class, as opposed to adding custom pythreejs features to the three.js wrappers.

**Comment by vidartf** [comment]
@honorabel That makes sense to me. Then I will add `Renderer` as a custom class , and try to have it match the current functionality as much as possible.

**Comment by martinal** [comment]
I get
```
index.js:44198 WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.
```
when mouse wheeling on a canvas, the culprit is an `isinstance` check in the OrbitControls.js that I'm guessing fails because of duplicate THREE module? This is a dev install.

**Comment by martinal** [comment]
[ ] The Setup instructions in the readme here suggest running `pip install` while in the js folder.

**Comment by martinal** [comment]
- [ ] Generated code that is placed in the repository should be deterministic so it doesn't result in unstaged changes just by running autogen.

The culprit is these dates in `enum.js` and `enums.py`
```
-Date: Fri Jun 02 2017 16:44:47 GMT+0200 (W. Europe Daylight Time)
+Date: Mon Aug 21 2017 08:14:37 GMT+0200 (CEST)
```
Considering that the files are checked in, the date is found in the git history so I suggest just removing these lines.

**Comment by martinal** [comment]
Following the Setup instructions in the current readme leads to quite a few errors on screen. It seems to work anyway, but would be nice to avoid.

Sample error:
```
> jupyter-threejs@0.4.0-alpha.0 autogen-wrappers /home/martinal/dev/vislibs/pythreejs/js
> node ./scripts/generate-wrappers.js

error creating wrapper: 
Error: invalid class name: Three
    at getExtraDefines (/home/martinal/dev/vislibs/pythreejs/js/scripts/generate-wrappers.js:130:15)
    at new JavascriptWrapper (/home/martinal/dev/vislibs/pythreejs/js/scripts/generate-wrappers.js:288:28)
    at createJavascriptWrapper (/home/martinal/dev/vislibs/pythreejs/js/scripts/generate-wrappers.js:509:23)
    at Glob.<anonymous> (/home/martinal/dev/vislibs/pythreejs/js/scripts/generate-wrappers.js:204:26)
    at emitOne (events.js:115:13)
    at Glob.emit (events.js:210:7)
    at Glob._emitMatch (/home/martinal/dev/vislibs/pythreejs/js/node_modules/glob/glob.js:489:8)
    at Glob._processSimple2 (/home/martinal/dev/vislibs/pythreejs/js/node_modules/glob/glob.js:705:8)
    at /home/martinal/dev/vislibs/pythreejs/js/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/martinal/dev/vislibs/pythreejs/js/node_modules/glob/glob.js:789:10)
    at lstatcb_ (/home/martinal/dev/vislibs/pythreejs/js/node_modules/glob/glob.js:764:12)
    at RES (/home/martinal/dev/vislibs/pythreejs/js/node_modules/inflight/inflight.js:31:16)
    at f (/home/martinal/dev/vislibs/pythreejs/js/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:153:5)
skipping: Three.js
```

**Comment by martinal** [comment]
- [ ] Objects are never deleted from ThreeCache, looks like a memory leak to me.

**Comment by martinal** [comment]
- [ ] The previewrenderer needs to set up the camera pointing towards the child from an appropriate distance. Easy to see the distance problem by just displaying a sphere with radius 10 (too small), 50 (too close), 100 (gone from view).

I can give it a shot, I have some similar computations in unray and aim to replace camera code with pythreejs.

**Comment by vidartf** [comment]
I think this can very soon replace master. Maybe we want to do a minor/patch release based on master first?

Remaining TODOs:
 - Audit functionality vs master (examples now work).
 - Make documentation: The code base is now complex enough that it is really needed. Especially for extension authors who want to integrate with pythreejs.

**Comment by jasongrout** [comment]
> I think this can very soon replace master. Maybe we want to do a minor/patch release based on master first?

Great idea. We can even update to ipywidgets 7 on master first. I was going to do that yesterday, but thought I'd ask you about the status first.

**Comment by vidartf** [comment]
> Great idea. We can even update to ipywidgets 7 on master first. I was going to do that yesterday, but thought I'd ask you about the status first.

Please go ahead with the v7 update, I should be able to resolve any merge conflicts from that quite easily unless it requires major refactorization. If you handle the release of that version, I can do the release of a beta for the next major version after this is merged.

**Comment by honorabel** [comment]
I wanted to briefly chime in here to cheers you guys for so much awesome work.  I'm so glad y'all have jumped in so amazingly here.  Glad the project is moving forward!

**Comment by vidartf** [comment]
@honorable It's like to turn it around and say thanks for a good start on what we wanted to do! :smile:

**Comment by jasongrout** [comment]
> Please go ahead with the v7 update, I should be able to resolve any merge conflicts from that quite easily unless it requires major refactorization. If you handle the release of that version, I can do the release of a beta for the next major version after this is merged.

@vidartf - I just released 0.4.0, compatible with ipywidgets v7. The updates are merged in to master at this point.

**Comment by vidartf** [comment]
@jasongrout Neat. I'll get around to solving the conflicts tomorrow. I'll then merge to master after I've made the dependence on the ipydatawidgets extension optional. Does that sound alright?

**Comment by jasongrout** [comment]
Sounds good to me. If we need to issue a patch release, we can fork at 0.4.0 and create an 0.4.x branch.

**Comment by vidartf** [comment]
The datawidgets extension has been made optional by splitting its JS package into two (one with widgets, one with serializers and everything else). Merging!

**Pull request merged**
