### PR TITLE
Upgrade to r112

### LINKED ISSUE #288: cannot use cubemap in pythreejs
when assign scene.background a CubeTexture, there is an error occured:

> TraitError: The 'background' trait of a Scene instance must be a valid HTML color, but a value of CubeTexture ...

and in pythreejs, cannot use the cubemap as the way in three.js.  because the CubeTextureLoader in pythreejs has no methods like load etc. and I cannot find any reference about this part.

anyone can help?
thanks

### PR DESCRIPTION
**Pull request by akaszynski**
Upgrade to threejs [r112](https://github.com/mrdoob/three.js/releases/tag/r112).

### Remaining wrappers
- [x] ~PMREMGenerator~ (API changed from method to class, delaying wrapper)
- [ ] LightProbe
- [ ] LightProbeHelper
- [ ] PositionalAudioHelper
- [ ] SphericalHarmonics3
- [ ] InstancedMesh
- [ ] AmbientLightProbe
- [ ] HemisphereLightProbe
- [ ] PointLightShadow
- [ ] WebGLMultisampleRenderTarget
- [ ] WebGLMultiviewRenderTarget
- [ ] DataTexture2DArray
- [ ] WebGLMultiview

### Changes
- [ ] .drawMode has been removed

### Bonus
- Resolve #288 by adding a loader for `CubeTexture`. Need this for the light probe tests.

### CODE REVIEW

**Comment by akaszynski** [comment]
@maartenbreddels, I'm going to try to support r112 first and then go from there.

@jasongrout, I'd like to help maintain this repository. Please message me at akascap@gmail.com if you think that's possible. I think this is an excellent repository and it's been 6 months since the last commit and around a year since a release. I'd really like to help.

**Comment by jasongrout** [comment]
@vidartf is the current main maintainer. @vidartf?

**Comment by jasongrout** [comment]
@vidartf was in the ipywidgets dev meeting this morning, so pinging him again.

**Comment by vidartf** [comment]
Hi @akaszynski , I'm around, and I'm more than happy to have others help out here! Thanks for volunteering! I am going to do an effort on this repo in the few coming days to add support for ipywidgets 8, but do not really plan to be working on features beyond that, so happy to leave that to you!

If you need me on a quicker turn-around than me checking my GH pings, you should be able to find my email address on the commits. Let's get a few PR's/commits through, and then get you set up with commit/publish rights after. Did you want me to review this PR in its current state?

**Pull request closed without merging**
