### PR TITLE
Added voxel painter example

### PR DESCRIPTION
**Pull request by nlooije**
The voxel painter example from Three.js website was modified into a
Ipython notebook using pythreejs

### CODE REVIEW

**Comment by nlooije** [comment]
I thought it would be interesting to port the voxel painter demo to pythreejs. 
I think the result is quite good except for some unimplemented features which are TODOs
The notebook can be viewed [here](https://github.com/nlooije/pythreejs/blob/examples/examples/threejs/voxel_painter.ipynb)
Is this something you would like added to your repo? I can try to port some other...

**Comment by jasongrout** [comment]
This is really cool!  Thanks!  Sorry it's taken a while to merge.

I'll probably move this up into the main examples directory after merging.

**Comment by jasongrout** [comment]
Never mind about that moving.  It's great where it is.  Thanks again!

**Comment by nlooije** [comment]
Hi Jason,

no problem! Best way to learn is to copy other people's work :)
are you interested in more examples like this?

Niels

On Fri, Oct 23, 2015 at 4:46 PM, Jason Grout <notifications@github.com>
wrote:

> Never mind about that moving. It's great where it is. Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jovyan/pythreejs/pull/28#issuecomment-150595319>.
>



-- 
Met vriendelijke groeten / Regards,
Niels Looije

**Comment by jasongrout** [comment]
I'm definitely interested in more cool examples.  Also, if there are changes to pythreejs that are needed to make things simpler, definitely open an issue.

**Pull request merged**
