### PR TITLE
Buffer attributes/geometry

### PR DESCRIPTION
**Pull request by vidartf**
Adds support for buffer attributes and geometries.

Point worth noting:
 - Adds a dependency on the newly create package `ipydatawidgets`, which is a helper package for arrays and widgets for sharing arrays between different widgets.
 - (Re-)introduces `PlainBufferGeometry` as a buffer geometry class that syncs its attributes to the python side.
 - Adds a custom factory function `PlainBufferGeometry.from_ref` that initializes a new `PlainBufferGeometry` as either a copy of another `BufferGeometry`, or as a conversion of a regular `Geometry`. This copy should then sync its attributes back to the kernel side.
 - To support `from_ref`, it introduces machinery for creating new widget models from the JS side.

See the updated example notebook(s) for behavior.

Based on #108.

### CODE REVIEW

**Comment by vidartf** [comment]
Note that with this PR, the autogen branch should be at the same level (nearly?) as the current master in terms of functionality, and that after the currently open PRs to the autogen branch are dealt with, one can consider merging the autogen branch into master.

**Comment by vidartf** [comment]
Emphasis: This PR adds the requirement that the ipydatawidgets frontend extension is installed as well.

**Comment by jasongrout** [comment]
@vidartf - feel free to merge this in if you feel it's ready.

**Comment by honorabel** [comment]
Apologies for not being able to review as much these days.  I'm so pumped you guys are really taking some huge steps with improving this lib!  The idea that buffer data can be passed back and forth efficiently is huge and I can only imagine what kind of cool demos this might enable!

**Comment by vidartf** [comment]
Just wanted to make sure you were comfortable adding a dependency on another extension.

**Comment by jasongrout** [comment]
> Just wanted to make sure you were comfortable adding a dependency on another extension.

I'm not opposed to the idea.

**Pull request merged**
