### PR TITLE
WIP upgrade to ipywidgets 7

### PR DESCRIPTION
**Pull request by jasongrout**
Also updates version to 0.4.0

CC @vidartf

### CODE REVIEW

**Comment by vidartf** [comment]
LGTM. I'm guessing it will still fail to install cleanly from source on Windows (see #83), but I'm not going block this on that (#83 is already included in #88).

**Comment by jasongrout** [comment]
Is it only installing from source that is a problem? Or is installing the built package also a problem on Windows?

**Comment by vidartf** [comment]
`pip install pythreejs` (uses wheel) works, `pip install https://github.com/jasongrout/pythreejs/archive/w7.zip` fails. The issue is with building the extension using npm.

```cmd
`npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
rebuilding js and css failed
missing files: ['C:\\Users\\vidar\\AppData\\Local\\Temp\\pip-t91jsk8h-build\\pythreejs\\static\\extension.js', 'C:\\Users\\vidar\\AppData\\Local\\Temp\\pip-t91jsk8h-build\\pythreejs\\static\\index.js']
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\vidar\AppData\Local\Temp\pip-t91jsk8h-build\setup.py", line 161, in <module>
    setup(**setup_args)
    File "C:\Miniconda3\envs\pythreetest\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
    File "C:\Miniconda3\envs\pythreetest\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
    File "C:\Miniconda3\envs\pythreetest\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
    File "C:\Users\vidar\AppData\Local\Temp\pip-t91jsk8h-build\setup.py", line 47, in run
    raise e
    File "C:\Users\vidar\AppData\Local\Temp\pip-t91jsk8h-build\setup.py", line 40, in run
    self.distribution.run_command('jsdeps')
    File "C:\Miniconda3\envs\pythreetest\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
    File "C:\Users\vidar\AppData\Local\Temp\pip-t91jsk8h-build\setup.py", line 111, in run
    raise ValueError(msg)
ValueError: Missing file: C:\Users\vidar\AppData\Local\Temp\pip-t91jsk8h-build\pythreejs\static\extension.js
npm is required to build a development version of widgetsnbextension
```

This is one of several issues that gets fixed by #83.

**Comment by jasongrout** [comment]
Sounds like we should review/merge #83, then rebase this on top of that?

**Comment by vidartf** [comment]
I merged #83 on top of this PR locally, and it installed from source (`pip install .`) without any issues. There was one merge conflict, but that was an identical change, so trivial to resolve. Merging #83 first might then be an OK solution, yes.

**Comment by jasongrout** [comment]
I merged #83 and then rebased this on top of master.

**Comment by vidartf** [comment]
I'm able to at least install this and run the examples. The code changes also make sense to me. So at least from my point of view this is good to go!

**Comment by jasongrout** [comment]
I just tried, and was having problems doing a `pip install .` from source - it seems that the static files were not copied to the /share/jupyter/nbextensions directory. I'm looking into it.

**Comment by vidartf** [comment]
Ah yes, I believe that feature is not available in the new code. If you'd be kind enough to contribute that feature to [jupyter-packaging](https://github.com/jupyter/jupyter-packaging) I will be able to quickly deploy that feature to many other projects as well! 👍 I never really got the hang of how to correctly implement that.

**Comment by jasongrout** [comment]
> If you'd be kind enough to contribute that feature to jupyter-packaging

See https://github.com/jupyter/jupyter-packaging/pull/17

**Comment by jasongrout** [comment]
I think this is good to go now. I'll merge and make the release.

**Pull request merged**
